name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - master  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Adjust the version as needed

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "VUE_APP_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env

      - name: Build app
        run: npm run build  # Builds the Vue app for production
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VUE_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}


      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist  # The folder to deploy (Vue builds to 'dist')
